import type { AlgoDef } from './types'

/* ---------------------------------------------------------------------------
 * Catalogue — the displayed Python is line-for-line what the runners trace.
 * Sources are arrays of lines so `index + 1` is the line number the runner
 * refers to; keep them in sync when editing either side (runners live in
 * ./runners/*).
 * ------------------------------------------------------------------------ */

export const ALGOS: AlgoDef[] = [
  {
    id: 'kahn',
    label: "Kahn's topological sort",
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O(V + E)',
    tagline: 'Peel the free nodes',
    lesson:
      'A node is "free" when nothing points at it any more. Kahn\'s repeatedly removes a free node and cuts its outgoing edges — if the queue ever dries up early, the leftovers form a cycle.',
    frontierLabel: 'queue',
    orderLabel: 'order',
    badgeLabel: 'in-degree',
    opsLabel: ['edges processed', 'nodes dequeued'],
    showWeights: false,
    code: [
      'from collections import deque',
      '',
      'def kahn(nodes, edges, adj):',
      '    # 1) count arrows into each node',
      '    indeg = {n: 0 for n in nodes}',
      '    for u, v in edges:',
      '        indeg[v] += 1',
      '',
      '    # 2) free nodes seed the queue',
      '    queue = deque(',
      '        n for n in nodes if indeg[n] == 0',
      '    )',
      '    order = []',
      '',
      '    # 3) peel the graph, layer by layer',
      '    while queue:',
      '        u = queue.popleft()',
      '        order.append(u)',
      '        for v in adj[u]:',
      '            indeg[v] -= 1',
      '            if indeg[v] == 0:',
      '                queue.append(v)',
      '',
      '    # leftovers ⇒ the graph had a cycle',
      '    if len(order) < len(nodes):',
      '        raise ValueError("cycle detected")',
      '    return order',
    ].join('\n'),
  },
  {
    id: 'bfs',
    label: 'Breadth-first search',
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O(V + E)',
    tagline: 'Explore in rings',
    lesson:
      'A queue makes exploration fair: everything at distance 1 is visited before anything at distance 2. That is why the first time BFS reaches a node, it arrived via a fewest-edges path.',
    frontierLabel: 'queue',
    orderLabel: 'visit order',
    badgeLabel: '',
    opsLabel: ['edges checked', 'nodes visited'],
    showWeights: false,
    code: [
      'from collections import deque',
      '',
      'def bfs(start, adj):',
      '    seen = {start}',
      '    queue = deque([start])',
      '    order = []',
      '',
      '    while queue:',
      '        u = queue.popleft()',
      '        order.append(u)',
      '        for v in adj[u]:',
      '            if v not in seen:',
      '                seen.add(v)',
      '                queue.append(v)',
      '',
      '    return order',
    ].join('\n'),
  },
  {
    id: 'dfs',
    label: 'Depth-first search',
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O(V + E)',
    tagline: 'Follow one thread to its end',
    lesson:
      'Recursion is a stack: DFS dives down one path until it dead-ends, then backtracks to the last fork. Swap BFS\'s queue for a stack and the exploration order flips from rings to threads.',
    frontierLabel: 'call stack',
    orderLabel: 'visit order',
    badgeLabel: '',
    opsLabel: ['edges checked', 'nodes visited'],
    showWeights: false,
    code: [
      'def dfs(start, adj):',
      '    seen = {start}',
      '    order = []',
      '',
      '    def visit(u):',
      '        order.append(u)',
      '        for v in adj[u]:',
      '            if v not in seen:',
      '                seen.add(v)',
      '                visit(v)  # dive deeper',
      '',
      '    visit(start)',
      '    return order',
    ].join('\n'),
  },
  {
    id: 'dijkstra',
    label: "Dijkstra's shortest paths",
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O((V + E) log V)',
    tagline: 'Settle the closest first',
    lesson:
      'Greedy, but safe: always settle the closest unsettled node. With no negative edges, nothing popped later can ever undercut it — so each pop is final. The violet edges are the best-known route home.',
    frontierLabel: 'priority queue',
    orderLabel: 'settled',
    badgeLabel: 'distance',
    opsLabel: ['relaxations', 'pops'],
    showWeights: true,
    code: [
      'import heapq',
      '',
      'def dijkstra(start, nodes, adj):',
      '    dist = {n: float("inf") for n in nodes}',
      '    dist[start] = 0',
      '    pq = [(0, start)]',
      '',
      '    while pq:',
      '        d, u = heapq.heappop(pq)',
      '        if d > dist[u]:',
      '            continue  # stale entry',
      '        for v, w in adj[u]:',
      '            if d + w < dist[v]:',
      '                dist[v] = d + w',
      '                heapq.heappush(pq, (d + w, v))',
      '',
      '    return dist',
    ].join('\n'),
  },
  {
    id: 'kruskal',
    label: "Kruskal's MST · Union-Find",
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O(E log E)',
    tagline: 'Cheapest edge that connects two islands',
    lesson:
      'Sort edges cheapest first; take one only if its ends are on different islands (Union-Find answers that in nearly O(1)) — same island means a cycle, so skip it. This greedy rule finds the minimum-cost network that connects everyone: the algorithm behind cable/pipeline layout, clustering, and image segmentation.',
    frontierLabel: 'edges left',
    orderLabel: 'MST edges',
    badgeLabel: 'root',
    opsLabel: ['find calls', 'MST edges'],
    showWeights: true,
    code: [
      'class UnionFind:',
      '    def __init__(self, nodes):',
      '        self.parent = {n: n for n in nodes}',
      '',
      '    def find(self, x):',
      '        while self.parent[x] != x:',
      '            # path halving: point at grandparent',
      '            self.parent[x] = self.parent[self.parent[x]]',
      '            x = self.parent[x]',
      '        return x',
      '',
      '    def union(self, a, b):',
      '        ra, rb = self.find(a), self.find(b)',
      '        if ra == rb:',
      '            return False  # same island: a cycle',
      '        self.parent[ra] = rb',
      '        return True',
      '',
      'def kruskal(nodes, edges):',
      '    dsu = UnionFind(nodes)',
      '    mst = []',
      '    for u, v, w in sorted(edges, key=lambda e: e[2]):',
      '        if dsu.union(u, v):',
      '            mst.append((u, v, w))',
      '    return mst',
    ].join('\n'),
  },
  {
    id: 'bellman-ford',
    label: 'Bellman-Ford',
    category: 'Graphs',
    viz: 'graph',
    complexity: 'O(V × E)',
    tagline: 'Slower, but handles negative edges',
    lesson:
      "Dijkstra assumes every edge only makes things worse (never negative) — a discount or a refund breaks that assumption. Bellman-Ford drops the priority queue and just relaxes every edge, V−1 times over — brute-force honest, and it can even prove a negative cycle exists by trying one round more. This is why routing protocols like RIP use it: correctness under any weight, not raw speed.",
    frontierLabel: 'edges this round',
    orderLabel: 'rounds',
    badgeLabel: 'distance',
    opsLabel: ['edge checks', 'relaxations'],
    showWeights: true,
    code: [
      'def bellman_ford(start, nodes, edges):',
      '    dist = {n: float("inf") for n in nodes}',
      '    dist[start] = 0',
      '',
      '    for i in range(len(nodes) - 1):',
      '        updated = False',
      '        for u, v, w in edges:',
      '            if dist[u] + w < dist[v]:',
      '                dist[v] = dist[u] + w',
      '                updated = True',
      '        if not updated:',
      '            break  # converged early',
      '',
      '    for u, v, w in edges:',
      '        if dist[u] + w < dist[v]:',
      '            raise ValueError("negative cycle")',
      '',
      '    return dist',
    ].join('\n'),
  },
  {
    id: 'astar',
    label: 'A* pathfinding',
    category: 'Graphs',
    viz: 'maze',
    complexity: 'O(E log V) typical',
    tagline: 'Dijkstra with a hunch',
    lesson:
      "Dijkstra expands uniformly in every direction because it knows nothing about where the goal is. A* adds a heuristic — here, straight-line-ish distance to the goal — so cells pointing toward the exit get explored first. Same guarantee of the shortest path (as long as the heuristic never overestimates), far less wasted exploration. This is the algorithm behind game pathfinding and GPS routing.",
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['neighbors checked', 'nodes expanded'],
    showWeights: false,
    code: [
      'import heapq',
      '',
      'def astar(start, goal, neighbors):',
      '    g = {start: 0}',
      '    open_set = [(heuristic(start, goal), start)]',
      '    came_from = {}',
      '',
      '    while open_set:',
      '        _, cur = heapq.heappop(open_set)',
      '        if cur == goal:',
      '            return reconstruct(came_from, cur)',
      '',
      '        for nxt in neighbors(cur):',
      '            tentative = g[cur] + 1',
      '            if tentative < g.get(nxt, float("inf")):',
      '                came_from[nxt] = cur',
      '                g[nxt] = tentative',
      '                f = tentative + heuristic(nxt, goal)',
      '                heapq.heappush(open_set, (f, nxt))',
      '',
      '    return None  # unreachable',
    ].join('\n'),
  },
  {
    id: 'nqueens',
    label: 'N-Queens (backtracking)',
    category: 'Backtracking',
    viz: 'queens',
    complexity: 'O(N!) worst case',
    tagline: 'Try, fail, undo',
    lesson:
      'Backtracking is depth-first search over decisions instead of nodes: place a queen, keep going as long as nothing conflicts, and the instant something does, undo the last choice and try the next option. No cleverness beyond systematic trial and error — checking safety before descending (not after) is what keeps it from ever exploring the full N! placements. The same shape solves Sudoku, maze generation, and constraint scheduling generally.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['safety checks', 'placements'],
    showWeights: false,
    code: [
      'def solve(board, col, n):',
      '    if col == n:',
      '        return True  # queen placed in every column',
      '',
      '    for row in range(n):',
      '        if is_safe(board, row, col, n):',
      '            board[col] = row       # place queen',
      '            if solve(board, col + 1, n):',
      '                return True',
      '            board[col] = -1        # backtrack',
      '',
      '    return False  # no row works in this column',
      '',
      'def is_safe(board, row, col, n):',
      '    for c in range(col):',
      '        r = board[c]',
      '        if r == row or abs(r - row) == abs(c - col):',
      '            return False',
      '    return True',
    ].join('\n'),
  },
  {
    id: 'bubble',
    label: 'Bubble sort',
    category: 'Sorting',
    viz: 'array',
    complexity: 'O(n²)',
    tagline: 'Neighbours swap until calm',
    lesson:
      'Each pass carries the biggest remaining value to the end like a bubble rising. Count the comparisons: quadratic hurts even at n = 10 — that is the whole argument for n log n sorts.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', 'swaps'],
    showWeights: false,
    code: [
      'def bubble_sort(a):',
      '    n = len(a)',
      '    for i in range(n - 1):',
      '        swapped = False',
      '        for j in range(n - 1 - i):',
      '            if a[j] > a[j + 1]:',
      '                a[j], a[j + 1] = a[j + 1], a[j]',
      '                swapped = True',
      '        if not swapped:',
      '            break  # already sorted',
      '    return a',
    ].join('\n'),
  },
  {
    id: 'insertion',
    label: 'Insertion sort',
    category: 'Sorting',
    viz: 'array',
    complexity: 'O(n²)',
    tagline: 'Sort like holding cards',
    lesson:
      'Grow a sorted prefix: pull the next value out, shift bigger ones right, drop it in its slot. On nearly-sorted input almost nothing shifts — insertion sort is secretly linear there.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', 'shifts'],
    showWeights: false,
    code: [
      'def insertion_sort(a):',
      '    for i in range(1, len(a)):',
      '        key = a[i]',
      '        j = i - 1',
      '        # shift bigger values right',
      '        while j >= 0 and a[j] > key:',
      '            a[j + 1] = a[j]',
      '            j -= 1',
      '        a[j + 1] = key',
      '    return a',
    ].join('\n'),
  },
  {
    id: 'quicksort',
    label: 'Quicksort',
    category: 'Sorting',
    viz: 'array',
    complexity: 'O(n log n) avg',
    tagline: 'Partition around a pivot',
    lesson:
      'Sweep everything smaller than the pivot to the left, then drop the pivot between the two camps — that slot is final forever (violet). Recursion sorts each side. Sorted input is the worst case (n²), which is why real libraries pick pivots at random.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', 'swaps'],
    showWeights: false,
    code: [
      'def quicksort(a, lo=0, hi=None):',
      '    if hi is None:',
      '        hi = len(a) - 1',
      '    if lo >= hi:',
      '        return a',
      '',
      '    pivot = a[hi]  # rightmost value',
      '    i = lo         # small-zone boundary',
      '    for j in range(lo, hi):',
      '        if a[j] < pivot:',
      '            a[i], a[j] = a[j], a[i]',
      '            i += 1',
      '    a[i], a[hi] = a[hi], a[i]  # pivot home',
      '',
      '    quicksort(a, lo, i - 1)',
      '    quicksort(a, i + 1, hi)',
      '    return a',
    ].join('\n'),
  },
  {
    id: 'mergesort',
    label: 'Merge sort',
    category: 'Sorting',
    viz: 'array',
    complexity: 'O(n log n)',
    tagline: 'Split, sort, zip together',
    lesson:
      'Halve until single elements, then merge back up: always take the smaller front of the two sorted halves. Guaranteed n log n — no bad inputs — at the price of scratch space for the halves.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', 'writes'],
    showWeights: false,
    code: [
      'def merge_sort(a, lo=0, hi=None):',
      '    if hi is None:',
      '        hi = len(a) - 1',
      '    if lo >= hi:',
      '        return a',
      '',
      '    mid = (lo + hi) // 2',
      '    merge_sort(a, lo, mid)',
      '    merge_sort(a, mid + 1, hi)',
      '',
      '    # merge the two sorted halves',
      '    left = a[lo:mid + 1]',
      '    right = a[mid + 1:hi + 1]',
      '    i = j = 0',
      '    k = lo',
      '    while i < len(left) and j < len(right):',
      '        if left[i] <= right[j]:',
      '            a[k] = left[i]; i += 1',
      '        else:',
      '            a[k] = right[j]; j += 1',
      '        k += 1',
      '    a[k:hi + 1] = left[i:] or right[j:]',
      '    return a',
    ].join('\n'),
  },
  {
    id: 'binary-search',
    label: 'Binary search',
    category: 'Searching',
    viz: 'array',
    complexity: 'O(log n)',
    tagline: 'Halve the haystack',
    lesson:
      'Sorted data lets one comparison discard half of what remains. 13 values need at most 4 probes; a billion need 30. Sortedness is what you are really paying for.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', ''],
    showWeights: false,
    code: [
      'def binary_search(a, target):',
      '    lo, hi = 0, len(a) - 1',
      '',
      '    while lo <= hi:',
      '        mid = (lo + hi) // 2',
      '        if a[mid] == target:',
      '            return mid',
      '        if a[mid] < target:',
      '            lo = mid + 1',
      '        else:',
      '            hi = mid - 1',
      '',
      '    return -1',
    ].join('\n'),
  },
  {
    id: 'heap',
    label: 'Binary min-heap',
    category: 'Data structures',
    viz: 'tree',
    complexity: 'O(log n) push/pop',
    tagline: 'The almost-sorted tree',
    lesson:
      'A heap promises one thing only: parent ≤ children. That keeps the minimum on top and makes repairs cheap — one root-to-leaf path, log n. And the tree is secretly just the array below it: node i\'s children live at 2i+1 and 2i+2.',
    frontierLabel: '',
    orderLabel: 'extracted',
    badgeLabel: '',
    opsLabel: ['comparisons', 'swaps'],
    showWeights: false,
    code: [
      'class MinHeap:',
      '    def __init__(self):',
      '        self.a = []',
      '',
      '    def push(self, x):',
      '        self.a.append(x)',
      '        i = len(self.a) - 1',
      '        while i > 0:',
      '            p = (i - 1) // 2',
      '            if self.a[p] <= self.a[i]:',
      '                break',
      '            self.a[p], self.a[i] = \\',
      '                self.a[i], self.a[p]',
      '            i = p',
      '',
      '    def pop(self):',
      '        a = self.a',
      '        a[0], a[-1] = a[-1], a[0]',
      '        m = a.pop()',
      '        i = 0',
      '        while True:',
      '            l, r = 2*i + 1, 2*i + 2',
      '            s = i',
      '            if l < len(a) and a[l] < a[s]: s = l',
      '            if r < len(a) and a[r] < a[s]: s = r',
      '            if s == i:',
      '                break',
      '            a[i], a[s] = a[s], a[i]',
      '            i = s',
      '        return m',
    ].join('\n'),
  },
  {
    id: 'bst',
    label: 'Binary search tree',
    category: 'Data structures',
    viz: 'tree',
    complexity: 'O(log n) avg',
    tagline: 'Binary search, grown as a tree',
    lesson:
      'Left < node < right at every fork: the insertion ORDER becomes a SHAPE. Search just re-walks the same decisions. Feed it sorted input and it degenerates into a linked list — that is exactly why balanced trees (AVL, red-black) exist.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['comparisons', ''],
    showWeights: false,
    code: [
      'def insert(root, v):',
      '    if root is None:',
      '        return Node(v)  # new leaf',
      '    if v < root.v:',
      '        root.left = insert(root.left, v)',
      '    else:',
      '        root.right = insert(root.right, v)',
      '    return root',
      '',
      'def search(root, t):',
      '    while root:',
      '        if t == root.v:',
      '            return True',
      '        root = (root.left if t < root.v',
      '                else root.right)',
      '    return False',
    ].join('\n'),
  },
  {
    id: 'linked-list',
    label: 'Linked list · reverse',
    category: 'Data structures',
    viz: 'list',
    complexity: 'O(n), O(1) space',
    tagline: 'Three pointers, flipped arrows',
    lesson:
      'Nodes never move — only the arrows flip. The whole trick is saving next BEFORE cutting curr.next, or the rest of the list floats away unreachable. Pointer discipline like this is the foundation of every linked structure you will ever debug.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['pointer reassignments', ''],
    showWeights: false,
    code: [
      'class Node:',
      '    def __init__(self, v, nxt=None):',
      '        self.v = v',
      '        self.next = nxt',
      '',
      'def reverse(head):',
      '    prev = None',
      '    curr = head',
      '    while curr:',
      '        nxt = curr.next   # save the rest',
      '        curr.next = prev  # flip the arrow',
      '        prev = curr       # advance',
      '        curr = nxt',
      '    return prev           # new head',
    ].join('\n'),
  },
  {
    id: 'trie',
    label: 'Trie (prefix tree)',
    category: 'Data structures',
    viz: 'tree',
    complexity: 'O(word length)',
    tagline: 'Words as paths',
    lesson:
      'One node per character: a word is a root-to-leaf path, and words sharing a prefix share a branch. Lookup cost depends on word length, not dictionary size — this is how autocomplete, spell-check and routing tables scale.',
    frontierLabel: '',
    orderLabel: 'completions',
    badgeLabel: '',
    opsLabel: ['char comparisons', 'nodes created'],
    showWeights: false,
    code: [
      'class TrieNode:',
      '    def __init__(self):',
      '        self.kids = {}',
      '        self.is_word = False',
      '',
      'def insert(root, word):',
      '    node = root',
      '    for ch in word:',
      '        if ch not in node.kids:',
      '            node.kids[ch] = TrieNode()',
      '        node = node.kids[ch]',
      '    node.is_word = True',
      '',
      'def complete(root, prefix):',
      '    node = root',
      '    for ch in prefix:',
      '        if ch not in node.kids:',
      '            return []  # dead end',
      '        node = node.kids[ch]',
      '    # walk the subtree, gather words',
      '    return collect(node, prefix)',
    ].join('\n'),
  },
  {
    id: 'hash-table',
    label: 'Hash table · chaining',
    category: 'Data structures',
    viz: 'hash',
    complexity: 'O(1) average',
    tagline: 'Any key, one jump',
    lesson:
      'key % 7 turns any key into a bucket index — lookup never scans the table, it jumps. Two keys landing in one bucket is a collision; the chain absorbs it. Keep the load factor low and chains stay short enough to call it O(1).',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['keys hashed', 'collisions'],
    showWeights: false,
    code: [
      'class HashTable:',
      '    def __init__(self, size=7):',
      '        self.buckets = [',
      '            [] for _ in range(size)',
      '        ]',
      '',
      '    def insert(self, key):',
      '        h = key % len(self.buckets)',
      '        chain = self.buckets[h]',
      '        if key in chain:',
      '            return  # already stored',
      '        chain.append(key)',
    ].join('\n'),
  },
  {
    id: 'lru-cache',
    label: 'LRU cache',
    category: 'Data structures',
    viz: 'lru',
    complexity: 'O(1) per op',
    tagline: 'A hash map that remembers order',
    lesson:
      'Neither structure alone is enough: a hash map gives O(1) lookup but no sense of order, a linked list gives order but O(n) lookup. Bolt them together — the map stores node references, the list tracks recency — and both operations stay O(1). This exact composition runs eviction in browsers, CDNs, and database buffer pools.',
    frontierLabel: '',
    orderLabel: '',
    badgeLabel: '',
    opsLabel: ['ops processed', 'evictions'],
    showWeights: false,
    code: [
      'class Node:',
      '    def __init__(self, k, v):',
      '        self.k, self.v = k, v',
      '        self.prev = self.next = None',
      '',
      'class LRUCache:',
      '    def __init__(self, cap):',
      '        self.cap = cap',
      '        self.map = {}',
      '        self.head = Node(0, 0)   # MRU sentinel',
      '        self.tail = Node(0, 0)   # LRU sentinel',
      '        self.head.next = self.tail',
      '        self.tail.prev = self.head',
      '',
      '    def _unlink(self, n):',
      '        n.prev.next, n.next.prev = n.next, n.prev',
      '',
      '    def _push_front(self, n):',
      '        n.next = self.head.next',
      '        n.prev = self.head',
      '        self.head.next.prev = n',
      '        self.head.next = n',
      '',
      '    def get(self, k):',
      '        if k not in self.map:',
      '            return -1',
      '        n = self.map[k]',
      '        self._unlink(n)',
      '        self._push_front(n)   # just used: most recent',
      '        return n.v',
      '',
      '    def put(self, k, v):',
      '        if k in self.map:',
      '            self._unlink(self.map[k])',
      '        n = Node(k, v)',
      '        self.map[k] = n',
      '        self._push_front(n)',
      '        if len(self.map) > self.cap:',
      '            lru = self.tail.prev          # least recently used',
      '            self._unlink(lru)',
      '            del self.map[lru.k]',
    ].join('\n'),
  },
  {
    id: 'knapsack',
    label: '0/1 Knapsack (DP)',
    category: 'Dynamic programming',
    viz: 'grid',
    complexity: 'O(n × capacity)',
    tagline: 'Every subproblem, solved once',
    lesson:
      'Each cell answers one narrow question — best value using the first i items within capacity c — and every cell after it reuses these answers instead of recomputing them from scratch. That reuse is the entire idea: exponential brute force (try every subset) collapses into one pass over a grid. The same pattern prices trading decisions, aligns DNA sequences, and diffs files.',
    frontierLabel: '',
    orderLabel: 'chosen items',
    badgeLabel: '',
    opsLabel: ['cells filled', 'backtrack steps'],
    showWeights: false,
    code: [
      'def knapsack(weights, values, cap):',
      '    n = len(weights)',
      '    dp = [[0] * (cap + 1) for _ in range(n + 1)]',
      '',
      '    for i in range(1, n + 1):',
      '        w, v = weights[i - 1], values[i - 1]',
      '        for c in range(cap + 1):',
      '            dp[i][c] = dp[i - 1][c]          # skip item i',
      '            if w <= c:',
      '                take = v + dp[i - 1][c - w]  # take item i',
      '                dp[i][c] = max(dp[i][c], take)',
      '',
      '    return dp[n][cap]',
    ].join('\n'),
  },
]
